### ISSUE TITLE
Feature request - image from URL

### ISSUE THREAD

**Issue by pbrandt1** [akfish/node-vibrant#4]
Would like to do something like `v = new Vibrant('http://slimages.macys.com/is/image/MCY/products/0/optimized/2899260_fpx.tif', opts)`

If this is something you'd like part of your lib, I can send you a PR :)

**Comment by akfish** [comment]
Sure. Your PL is definitely welcome. :)

**Comment by ScottKriegerPD** [comment]
Looking for this feature as well. Any progress on this?

**Comment by pbrandt1** [comment]
yeah, i've got it working in node, but wasn't able to get gulp to do the browser part.  Maybe you know what's wrong?  

```
peter@sonux /data/code/node-vibrant (image-url) gulp browser
[11:01:15] Requiring external module coffee-script/register
[11:01:16] Using gulpfile /data/code/node-vibrant/gulpfile.coffee
[11:01:16] Starting 'coffee'...
[11:01:16] Finished 'coffee' after 236 ms
[11:01:16] Starting 'browser'...
[11:01:16] 'browser' errored after 140 ms
[11:01:16] TypeError: Path must be a string. Received Readable {
  _readableState: 
   ReadableState {
     highWaterMark: 16,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     objectMode: true,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _read: [Function] }
  at assertPath (path.js:8:11)
  at Object.posix.resolve (path.js:424:5)
  at module.exports (/data/code/node-vibrant/node_modules/vinyl-source-stream/index.js:13:34)
  at /data/code/node-vibrant/node_modules/gulp-heap/lib/convert.js:13:16
  at /data/code/node-vibrant/node_modules/gulp-heap/lib/core.js:179:26
  at Array.forEach (native)
  at fn (/data/code/node-vibrant/node_modules/gulp-heap/lib/core.js:164:21)
  at Gulp.<anonymous> (/data/code/node-vibrant/node_modules/gulp-heap/lib/core.js:177:20)
  at Array.forEach (native)
  at Gulp.fn (/data/code/node-vibrant/node_modules/gulp-heap/lib/core.js:164:21)
  at module.exports (/data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at /data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
  at f (/data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at DestroyableTransform.onend (/data/code/node-vibrant/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
  at emitNone (events.js:72:20)
  at DestroyableTransform.emit (events.js:166:7)
  at /data/code/node-vibrant/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at doNTCallback0 (node.js:407:9)
  at process._tickDomainCallback (node.js:377:13)
```

**Comment by ScottKriegerPD** [comment]
Staring at that same error on my fork. I've yet to dig into the code to decipher, but gulp browser gives me the same error. I'm after doing this in node rather than the browser though if you have some pointers.

**Comment by akfish** [comment]
I'll take a look and get back to you both.

**Comment by akfish** [comment]
Looks like some weird cross-platform issues somewhere along the build tool chain. 

Don't worry about it though since this feature is node.js-only and `gulp browser` builds browser target. Changes in `node-image.coffee` won't affect those. Use `gulp coffee` and `gulp test` should do for this PL's purpose.

**Comment by akfish** [comment]
It turns out this project is still using an older version of my `gulp-heap` package. The bug causing this problem was fixed in later version. 
Try run `npm install gulp-heap@2.0.0-alpha.1`. See if that will fix the problem.

**Comment by ScottKriegerPD** [comment]
That did fix the issue.
`
scott:node-vibrant scottkrieger$ gulp browser
[12:28:40] Requiring external module coffee-script/register
[12:28:41] Using gulpfile ~/node-vibrant/gulpfile.coffee
[12:28:41] Starting 'coffee'...
[12:28:41] Finished 'coffee' after 7.42 ms
[12:28:41] Starting 'browser'...
[12:28:42] Finished 'browser' after 235 ms
`
